# Generated by Django 4.1.2 on 2022-11-02 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietario', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('num_chassi', models.CharField(max_length=17, unique=True)),
                ('utima_localizacao', models.CharField(max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.empresa')),
            ],
        ),
    ]
