# Generated by Django 4.1.2 on 2022-11-03 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_veiculo_foto_carro'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.empresa'),
        ),
        migrations.AddField(
            model_name='user',
            name='nv_acesso',
            field=models.IntegerField(choices=[(1, 'Nivel1'), (2, 'Nivel2'), (3, 'Nivel3')], null=True, verbose_name='Nível de Aceso'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome da Empresa'),
        ),
    ]
