# Generated by Django 4.1.2 on 2022-11-03 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_empresa_user_nv_acesso_alter_empresa_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.empresa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nv_acesso',
            field=models.IntegerField(choices=[(1, 'Nivel1'), (2, 'Nivel2'), (3, 'Nivel3')], verbose_name='Nível de Aceso'),
        ),
    ]
