# Generated by Django 4.1.2 on 2022-11-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_empresa_alter_user_nv_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nv_acesso',
            field=models.IntegerField(choices=[(1, 'Nivel1'), (2, 'Nivel2'), (3, 'Nivel3')], default=1, verbose_name='Nível de Aceso'),
        ),
    ]
