# Generated by Django 4.1.2 on 2022-11-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_user_nv_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nome',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=50, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nv_acesso',
            field=models.IntegerField(choices=[(1, 'Nivel1'), (2, 'Nivel2')], default=1, verbose_name='Nível de Aceso'),
        ),
    ]
