# Generated by Django 4.1.2 on 2022-11-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_user_nome_alter_empresa_cnpj_alter_user_nv_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome Completo'),
        ),
    ]
