# Generated by Django 4.1.2 on 2022-11-05 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_user_nome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Veiculo',
        ),
    ]
