# Generated by Django 4.1.2 on 2022-11-29 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('photo_car', models.ImageField(upload_to='main/carros/%Y/%m/%d/', verbose_name='Imagem do Veículo')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo do Veículo')),
                ('color', models.CharField(max_length=10, verbose_name='Cor do veículo')),
                ('country', models.CharField(default='Brasil', max_length=50, verbose_name='País')),
                ('license_plate', models.CharField(max_length=7, unique=True, verbose_name='Placa')),
                ('num_frame', models.CharField(max_length=20, unique=True, verbose_name='Número do Chassi')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.firm')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleHistoric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('latitude', models.CharField(max_length=20, null=True)),
                ('longitude', models.CharField(max_length=20, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.vehicle')),
            ],
        ),
    ]
