# Generated by Django 4.1.2 on 2022-11-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='utima_localizacao',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='longitude',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
