# Generated by Django 4.1.2 on 2022-11-12 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0003_veiculo_cor_alter_veiculo_foto_carro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='longitude',
        ),
    ]
