# Generated by Django 4.1.2 on 2022-11-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0004_remove_veiculo_latitude_remove_veiculo_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculohistorico',
            name='horario',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
