# Generated by Django 4.1.2 on 2022-11-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0007_alter_veiculohistorico_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculohistorico',
            name='horario',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
